---
name: release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Get a preview of the pending release"
        type: boolean
        required: true
        default: false
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
    branches:
      - "main"

jobs:
  ko-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          dry_run: "${{ github.event.inputs.dry_run }}"
          working_directory: ./.github
      - name: Setup ko-build
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          ko build --bare ./cmd/github-app-secret -t $TAG \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --image-refs refs.txt
        env:
          TAG: ${{ steps.semantic-release.outputs.new_release_version }}
      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.4.0
      - name: Sign images
        if: steps.semantic-release.outputs.new_release_published == 'true'
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cat refs.txt | xargs -n1 cosign sign --yes
